galaxy_info:
  author: logan
  description: Setup resolvconf/resolv.conf
  license: Apache2
  min_ansible_version: 1.6.6
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - dns
    - resolution
