---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Because there is no specific "horizon" command this method
#  is looking for the "keystone" command to set the horizon
#  command path.
- name: Get horizon command path
  command: which keystone
  register: horizon_command_path
  when:
    - not horizon_venv_enabled | bool
  tags:
    - horizon-command-bin

- name: Set horizon command path
  set_fact:
    horizon_bin: "{{ horizon_command_path.stdout | dirname }}"
  when:
    - not horizon_venv_enabled | bool
  tags:
    - horizon-command-bin

- name: Setup Horizon config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "horizon_local_settings.py.j2", dest: "/etc/horizon/local_settings.py", mode: "0644" }
    - { src: "horizon-manage.py.j2", dest: "{{ horizon_bin }}/horizon-manage.py", mode: "0755" }
  notify: Restart apache2
  tags:
    - horizon-configs

- name: Ensure horizon policy directory
  file:
    path: "/etc/horizon/policy"
    state: directory
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0755"
  tags:
    - horizon_configs

- name: Copy service policies
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "keystone_policy.json.j2"
      dest: "/etc/horizon/policy/keystone_policy.json"
      config_overrides: "{{ keystone_policy_overrides|default({}) }}"
      config_type: "json"
    - src: "nova_policy.json.j2"
      dest: "/etc/horizon/policy/nova_policy.json"
      config_overrides: "{{ nova_policy_overrides|default({}) }}"
      config_type: "json"
    - src: "cinder_policy.json.j2"
      dest: "/etc/horizon/policy/cinder_policy.json"
      config_overrides: "{{ cinder_policy_overrides|default({}) }}"
      config_type: "json"
    - src: "glance_policy.json.j2"
      dest: "/etc/horizon/policy/glance_policy.json"
      config_overrides: "{{ glance_policy_overrides|default({}) }}"
      config_type: "json"
    - src: "heat_policy.json.j2"
      dest: "/etc/horizon/policy/heat_policy.json"
      config_overrides: "{{ heat_policy_overrides|default({}) }}"
      config_type: "json"
    - src: "neutron_policy.json.j2"
      dest: "/etc/horizon/policy/neutron_policy.json"
      config_overrides: "{{ neutron_policy_overrides|default({}) }}"
      config_type: "json"
    - src: "ceilometer_policy.json.j2"
      dest: "/etc/horizon/policy/ceilometer_policy.json"
      config_overrides: "{{ ceilometer_policy_overrides|default({}) }}"
      config_type: "json"
  notify: Restart apache2
  tags:
    - horizon-configs

- name: Create horizon links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    state: "link"
  with_items:
    - { src: "/etc/horizon/local_settings.py", dest: "{{ horizon_lib_dir }}/openstack_dashboard/local/local_settings.py" }
    - { src: "/etc/horizon/policy", dest: "{{ horizon_lib_dir }}/openstack_dashboard/local/policy" }
  tags:
    - horizon-configs

- name: Collect and compress static files
  command: "{{ item }}"
  sudo: yes
  sudo_user: "{{ horizon_system_user_name }}"
  with_items:
    - "{{ horizon_bin }}/horizon-manage.py collectstatic --noinput"
    - "{{ horizon_bin }}/horizon-manage.py compress --force"
  tags:
    - horizon-configs
    - horizon-static-collect
    - horizon-command-bin

- name: Setup Horizon config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
  with_items:
    - { src: "horizon_django.wsgi.j2", dest: "{{ horizon_lib_wsgi_file }}" }
  notify: Restart apache2
  tags:
    - horizon-configs
    - horizon-wsgi-venv

- name: Create cutomization module directory
  file:
    path: "{{ horizon_lib_dir }}/{{ horizon_customization_module }}"
    state: directory
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0755"
  when: horizon_customization_module is defined
  tags:
    - horizon-configs

- name: Drop horizon customization module
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "{{ horizon_customization_module }}.py.j2", dest: "{{ horizon_lib_dir }}/{{ horizon_customization_module }}/__init__.py", mode: "0644" }
  notify: Restart apache2
  when: horizon_customization_module is defined
  tags:
    - horizon-configs
