---
unbound_conf_dir: /etc/unbound/unbound.conf.d

unbound_upstream_resolvers: "{{ lxc_cache_resolvers }}"
unbound_localzone_mode: static
unbound_root_zone: openstack
unbound_regional_zone: "{{ service_region }}.{{ unbound_root_zone }}"

#see /etc/default/unbound for info on these
unbound_trust_anchor_update: true
unbound_resolvconf: true
unbound_resolvconf_forwarders: false

#deploys to server like priority-template.conf
#so for example, 000-server.conf in unbound_conf_dir which is in the include path by default
unbound_configuration_templates:
  - template: "server.conf"
    priority: 0
  - template: "openstack.conf"

#additional records example:
#unbound_records:
#  - { host: hostname1.openstack, val: 10.10.10.1, type: A }
#  - { host: hostname2.openstack, val: 10.10.10.2, type: A }
unbound_records: []

unbound_apt_packages:
  - unbound
  - unbound-anchor
  - unbound-host
