---

- name: Install unbound DNS resolvers
  hosts:
    - "{{ host_group|default('hosts') }}"
    - all_containers
  max_fail_percentage: 20
  user: root
  pre_tasks:
    - name: Wait for container ssh
      wait_for:
        port: "22"
        delay: "{{ ssh_delay }}"
        search_regex: "OpenSSH"
        host: "{{ ansible_ssh_host }}"
      delegate_to: "{{ physical_host }}"
      when: container_config is defined and container_config | changed
      register: ssh_wait_check
      until: ssh_wait_check | success
      retries: 3
      tags:
        - ssh-wait
  roles:
    - role: "unbound_server"
      when:
        - groups['unbound'] is defined
        - inventory_hostname in groups['unbound']
      tags:
        - unbound_server
    - role: "unbound_client"
      when:
        - groups['unbound'] is defined
        - inventory_hostname not in groups['unbound']
      tags:
        - unbound_client
    - role: "system_crontab_coordination"
      tags:
        - "system-crontab-coordination"
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
